services:
  docs:
    image: revenue_intelligence_local_docs
    container_name: revenue_intelligence_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./revenue_intelligence:/app/revenue_intelligence:z
    ports:
      - '9000:9000'
    command: /start-docs
