# Generated by Django 5.2.3 on 2025-07-02 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='Account ID')),
                ('name', models.CharField(max_length=255, verbose_name='Account Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Job Title')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='analytics.account')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Opportunity Name')),
                ('stage', models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualification', 'Qualification'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Prospecting', max_length=50, verbose_name='Stage')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('probability', models.DecimalField(decimal_places=2, help_text='A value between 0.00 and 1.00', max_digits=3, verbose_name='Probability')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Close Date')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Created Date')),
                ('next_step', models.CharField(blank=True, max_length=255, null=True, verbose_name='Next Step')),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lead Source')),
                ('opportunity_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='analytics.account')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='analytics.contact')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-amount'],
            },
        ),
    ]
