# Generated by Django 5.2.3 on 2025-07-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='lead_source',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='next_step',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Next Step'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Type'),
        ),
    ]
